trigger:
  branches:
    include:
      - main # Adjust this to the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest' # You can change this if you're using a specific environment

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Specify Node.js version for Angular 17
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production
  displayName: 'Build Angular App'

# Define Docker build and push
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: '<your-docker-registry-service-connection>' # Define your Docker registry service connection in Azure DevOps
    repository: '<your-docker-registry>/<your-repository>' # Replace with your Docker repository
    command: buildAndPush
    Dockerfile: '**/Dockerfile' # Path to your Dockerfile
    tags: |
      $(Build.BuildId)

- task: Docker@2
  displayName: 'Run Docker Container'
  inputs:
    containerRegistry: '<your-docker-registry-service-connection>'
    repository: '<your-docker-registry>/<your-repository>'
    command: 'run'
    arguments: '-d -p 80:80 $(Build.BuildId)'
